lc=python3
input=output.txt
input=output-with-identifier.txt
input=output-moves-between-all-images.txt
input=eight-output.txt
input=four-200-time-step.txt
# input=four-output.txt

all: build

build:
	$(lc) plot.py $(input)
